feat(next13-zustand-bulma): add counter component
thisdot/starter.dev pull request #1181
Opened 2023-03-14 08:28 UTC by BigAB

## Type of change

Add a Counter Component to the `next13-zustand-bulma` starter kit

## Summary of change
- added client counter component, test, and story
- put component in counter-example page
-

## Checklist

- [x] These changes follow the [contributing guidelines](https://github.com/thisdot/starter.dev/blob/main/CONTRIBUTING.md)
- [x] Changes for this new starter kit are being pushed to an integration branch instead of main
- [x] All dependencies are version locked
- [x] This fix resolves #994 
- [x] I have verified the fix works and introduces no further errors

2023-03-14 19:57 UTC, jdwilkin4 requested changes
Tested it out locally and it looks good.
I did notice that for small tablet sizes the buttons are squished together. 
Maybe we can go to a column at that point

<img width="687" alt="Screenshot 2023-03-14 at 12 57 25 PM" src="https://user-images.githubusercontent.com/67210629/225122064-85a9544c-ca42-473b-96a5-e577bde7cdbd.png">

2023-03-14 23:24 UTC, BigAB commented
> Tested it out locally and it looks good. I did notice that for small tablet sizes the buttons are squished together. Maybe we can go to a column at that point

@jdwilkin4  Fixed and force pushed again.

I had to fix a lot of things actually, including storybook, how to add global styles to storybook, and fix the tests to work with zustand.  But here it is:

<img width="664" alt="Screenshot 2023-03-14 at 4 41 47 PM" src="https://user-images.githubusercontent.com/76821/225163592-ecb68084-7fae-4a91-a178-78af8a93eeca.png">

<img width="629" alt="Screenshot 2023-03-14 at 4 42 12 PM" src="https://user-images.githubusercontent.com/76821/225163608-16993ff1-6eb6-4231-a9b3-3391b7578436.png">

With the addition of the tests, I actually  now need to wait for #1177 to be merged before I can merge this, I think.

2023-03-15 00:53 UTC, jdwilkin4 commented on starters/next13-zustand-bulma/.storybook/with-font-decorator.tsx
> +};
A note for later:
I think we should add a sentence or two about this google font and decorator stuff because I believe this is new for Next 13

2023-03-15 00:55 UTC, jdwilkin4 approved these changes
tested it again locally, and it works for me 👍

2023-03-15 20:31 UTC, merged