[Core] - Commit hooks implementation
thisdot/starter.dev pull request #286
Opened 2022-07-27 17:34 UTC by SDaian

## Starterrs
     [ ] - angular-ngrx-scss

Closes #285

2022-08-04 15:56 UTC, dustinsgoodman commented on starters/next-react-query-tailwind/.husky/pre-push
> +cd "$(dirname -- "$0")" && npm test
These husky scripts are more focused on the generated kits and not the kit in this context fwiw. If this works in a generated kit, that's great though.

2022-08-04 15:57 UTC, dustinsgoodman requested changes
Couple of small comments that need to be addressed. You also mentioned it wasn't working on the CRA - I'd like more details on that so we can debug further.

2022-08-04 15:57 UTC, dustinsgoodman commented on starters/next-react-query-tailwind/package.json
> +    "husky": "^8.0.1",
We want to version lock anything we add for dependency reasons.

2022-08-19 15:00 UTC, dustinsgoodman requested changes
Where's the nuxt CI?

2022-08-23 13:37 UTC, SDaian commented on starters/angular-ngrx-scss/package.json
> +    "pretty-quick": "^3.1.3",
this package is for only to run `Prettier` on your changed files:
![image](https://user-images.githubusercontent.com/14813235/186172490-485bf008-b630-4880-a9a2-e2358323391c.png)

[Link](https://www.npmjs.com/package/pretty-quick)

2022-08-23 16:07 UTC, SDaian commented on .github/workflows/ci-angular-apollo-tailwind.yml
> +        run: npm i
cannot run `npm ci` because the starters doesn't have package-lock.json according to the logs

2022-08-23 16:41 UTC, dustinsgoodman commented on starters/angular-ngrx-scss/package.json
> +    "pretty-quick": "^3.1.3",
Got it - I think I'm used to lint-staged and am less familiar with this. I don't know if anyone else has an opinion but I'm game for this if it works. 😄

2022-08-23 16:41 UTC, dustinsgoodman commented on .github/workflows/ci-angular-apollo-tailwind.yml
> +        run: npm i
That makes sense

2022-11-15 18:55 UTC, lindakatcodes commented on starters/angular-apollo-tailwind/package.json
> +    "name": "angular-apollo-tailwind",
@dustinsgoodman The prettier config for this kit has `tabWidth` set to 4.

2022-11-15 18:58 UTC, dustinsgoodman commented on starters/angular-apollo-tailwind/package.json
> +    "name": "angular-apollo-tailwind",
Can we change it back to 2?

2022-11-15 18:59 UTC, lindakatcodes commented on starters/angular-apollo-tailwind/package.json
> +    "name": "angular-apollo-tailwind",
Yep I can do that!

2022-11-15 21:03 UTC, lindakatcodes commented
This PR has now been updated to include a workflow for the Nuxt2-Pinia starter kit, as well as removing the husky dependencies. 

There should now be a workflow file for each of the requested starter kits that uses that kit's package.json file to get the Node version (so it matches what the project needs), and runs linting and testing for each kit on PRs and push commands.

There's still a few things to work out within the checks themselves - Nuxt has an issue with it's own internal version of Husky, and CRA is having a few linting issue that should be cleaned up. But the files themselves I believe should be in good enough shape to review. The other fixes can come in later in this PR or a separate one, whichever is preferred.

2022-11-16 07:38 UTC, TapaiBalazs reviewed
LGTM so far, let me know if you need help with the remaining failing CIs

2022-11-28 19:59 UTC, morgnism approved these changes
LGTM

2022-11-28 20:10 UTC, merged