fix: make pre-scroll / post-scroll buttons on kit details page consistent
thisdot/starter.dev pull request #306
Opened 2022-08-22 13:49 UTC by kodejuice

#290 

Make the pre-scroll & post-scoll buttons on the kit details page consisten

2022-08-22 15:12 UTC, danecando requested changes
Needs better PR description and screenshots. 

It's always good to link the ticket which you did but the PR description shouldn't just be the title of the ticket. Reviewer can clicked the linked ticket to see more about it. The PR description should highlight what exact changes that it makes to complete the ticket. This one specifically should also include screenshots to showcase what changed visually.

2022-08-22 15:26 UTC, kodejuice commented
> Needs better PR description and screenshots.
> 
> It's always good to link the ticket which you did but the PR description shouldn't just be the title of the ticket. The reviewer can click the linked ticket to see more about it. The PR description should highlight what exact changes that the PR makes to complete the ticket. This one specifically should also include screenshots to showcase what changed visually.

Was going to do that, i.e include a video demonstration, but realized i don't have screen recorder.
Will include screenshots

2022-08-22 16:07 UTC, dustinsgoodman commented
> > Needs better PR description and screenshots.
> > It's always good to link the ticket which you did but the PR description shouldn't just be the title of the ticket. The reviewer can click the linked ticket to see more about it. The PR description should highlight what exact changes that the PR makes to complete the ticket. This one specifically should also include screenshots to showcase what changed visually.
> 
> Was going to do that, i.e include a video demonstration, but realized i don't have screen recorder. Will include screenshots

Try https://www.loom.com/ for screen recordings. 😉

2022-08-23 15:43 UTC, danecando requested changes
Thanks for adding the screen recording! Would still be nice to add some info about the changes you made.

It looks like we still need to update the link class styles to only be underlined when hovered or active looking at the #290

2022-08-24 20:22 UTC, danecando reviewed
Seems like it's still probably underlined before you hover over it since the css in the link class wasn't changed. You'll need to update the link css in the main css file

2022-08-25 10:24 UTC, kodejuice commented
> Seems like it's still probably underlined before you hover over it since the css in the link class wasn't changed. You'll need to update the link css in the main css file

My bad, i only applied it to the nav links, updated now

2022-08-25 14:01 UTC, danecando approved these changes

2022-08-26 11:12 UTC, merged