feat: [sveltekit-pod] 4. Add Kit on the main site
thisdot/starter.dev pull request #452
Opened 2022-10-24 16:47 UTC by ihardz

resolves #384

> # Background
> The website has attempted to include all the kits appropriately but may need some added configuration to display correctly.
> 
> # Acceptance
> - [x] Ensure the kit displays on the website
> - [x] Add any missing logos for technologies as needed

Result: (UPDATED)

![image](https://user-images.githubusercontent.com/31627738/197722029-fb808092-ee96-4a3d-90c9-a86f28fa6737.png)

2022-10-24 17:35 UTC, dustinsgoodman commented
@ihardz I'd change it so that SvelteKit is the "Framework" then remove Svelte. I think this is a case where we're just having 2 items and should update design to support the fact that there's only 2.

2022-10-25 06:32 UTC, Zelig880 requested changes

2022-10-25 06:32 UTC, Zelig880 commented on packages/website/src/config.tsx
> +  },
extra space here

2022-10-25 06:32 UTC, Zelig880 commented on starters/svelte-kit-scss/package.json
> +    "sass"
extra space here

2022-10-25 08:52 UTC, Zelig880 approved these changes

2022-10-25 08:52 UTC, merged