[GraphQL-Serverless-Contentful] Add seeding script to the starter kit
thisdot/starter.dev pull request #585
Opened 2022-12-02 13:43 UTC by markshenouda

## Type of change

- [ ] Documentation change
- [ ] Bug fix

## Summary of change

## Checklist

- [x] These changes follow the [contributing guidelines](https://github.com/thisdot/starter.dev/blob/main/CONTRIBUTING.md)
- [x] This starter kit has been approved by the maintainers
- [x] Changes for this new starter kit are being pushed to an integration branch instead of main
- [x] All dependencies are version locked
- [ ] This fix resolves #
- [x] I have verified the fix works and introduces no further errors

2023-01-12 15:58 UTC, mbicknese requested changes

2023-01-12 15:58 UTC, mbicknese commented on starters/graphql-serverless-contentful/package.json
> +    "typescript": "4.8.4"و
@markshenouda , what's this? 😅

2023-01-12 16:03 UTC, mbicknese approved these changes

2023-01-13 06:14 UTC, markshenouda commented on starters/graphql-serverless-contentful/package.json
> +    "typescript": "4.8.4"و
Oh no🤦‍♂️

2023-01-13 06:14 UTC, merged