feat(solidjs-pod): Fix starter kit greeting component
thisdot/starter.dev pull request #837
Opened 2023-01-20 17:09 UTC by SDaian

## Type of change

- [ ] Documentation change
- [x] Bug fix

## Summary of change

- [x] there is an issue with the network call, which needs to be updated for Netlify
- [x] the input field needs to go away, it's not necessary. See SvelteKit as an example, or the NextJS kit - both examples of how this should work

Closes: #823

2023-01-20 17:13 UTC, Megio approved these changes
LGTM 🛸

2023-01-23 08:18 UTC, hdJerry commented on starters/solidjs-tailwind/src/components/FetchExample/Greeting.spec.jsx
> +    expect(wrapper.findByText('This Dot Labs!')).toBeTruthy();
This test isn't valid as whatever test you put still passes.

eg
```js
 expect(wrapper.findByText('nothing')).toBeTruthy();
```

2023-01-23 08:19 UTC, hdJerry commented on starters/solidjs-tailwind/src/components/FetchExample/Greeting.spec.jsx
> +    window.fetch = () => {
Not sure the purpose of this as its absence doesn't affect the result

2023-01-23 08:26 UTC, hdJerry commented on starters/solidjs-tailwind/src/components/FetchExample/Greeting.spec.jsx
> +    expect(wrapper.findByText('This Dot Labs!')).toBeTruthy();
this should be the test, you notice the await also.

```js
expect(await wrapper.findByText('Hi Learner from This Dot Labs!')).toBeTruthy();
```

As we are mocking the API, you can check the mock folder to see what we mocked

2023-01-23 08:31 UTC, hdJerry requested changes
Please, check my comments

2023-01-23 08:53 UTC, hdJerry requested changes

2023-01-23 08:53 UTC, hdJerry commented on starters/solidjs-tailwind/src/components/FetchExample/Greeting.jsx
>  import { createEffect, createResource, createSignal } from 'solid-js';
Please remove unused imports

2023-01-23 14:48 UTC, Megio approved these changes
LGTM

2023-01-23 16:00 UTC, merged