[serverless-apollo-contentful] Create Technology model
thisdot/starter.dev pull request #861
Opened 2023-01-25 11:35 UTC by mbicknese

## Type of change

- [ ] Documentation change
- [ ] Bug fix
- [x] Feature 

## Summary of change

This removes the Post and Comment model in favour of the Technology model, as is the new standard according to the specification.

This PR replaces #835 and #836. Credits to @kodejuice and @iansamz for paving the way.

## Checklist

- [x] These changes follow the [contributing guidelines](https://github.com/thisdot/starter.dev/blob/main/CONTRIBUTING.md)
- [x] Changes for this new starter kit are being pushed to an integration branch instead of main
- [x] All dependencies are version locked
- [x] This fix resolves #851
- [x] I have verified the fix works and introduces no further errors

2023-01-25 14:40 UTC, iansamz approved these changes

2023-01-25 14:40 UTC, iansamz commented on starters/graphql-serverless-contentful/src/schema/technology/technology.resolver.test.ts
> +client.getSpace = (key) =>
You can add types for Space & Environment as done in #835, to avoid using @ts-ignore

2023-01-26 11:48 UTC, iansamz requested changes
Just left with this to merge

2023-01-26 11:48 UTC, iansamz commented on starters/graphql-serverless-contentful/src/schema/technology/technology.resolver.test.ts
> +		let created_technology: any;
This is currently declared but not used

2023-01-26 12:13 UTC, mbicknese commented on starters/graphql-serverless-contentful/src/schema/technology/technology.resolver.test.ts
> +		let created_technology: any;
```suggestion
```

2023-01-26 12:18 UTC, iansamz approved these changes

2023-01-26 12:26 UTC, merged