feat(solidstart): Add kit to CLI
thisdot/starter.dev pull request #926
Opened 2023-01-30 15:41 UTC by SDaian

## Type of change

- [x] Documentation change
- [ ] Bug fix

## Summary of change

- [x] Added kit to the CLI

Closes: #910

2023-01-30 15:56 UTC, hdJerry commented on starters/solidstart-tanstackquery-tailwind-modules/package.json
> +    "tan-stack-query",
tanstack is on word

2023-01-30 16:14 UTC, Megio reviewed
In the package.json file I see two times this `"@testing-library/jest-dom"`

The rest is good! 🙌🏻

2023-01-31 09:17 UTC, hdJerry approved these changes
You Rock Sir!

2023-01-31 14:08 UTC, hdJerry commented on starters/solidstart-tanstackquery-tailwind-modules/package.json
> +    "solidjs",
solidstart

2023-01-31 14:09 UTC, hdJerry requested changes
Please make this adjustment above

2023-01-31 14:12 UTC, hdJerry approved these changes
Thanks sir

2023-01-31 14:12 UTC, merged